services:
  ml-api:
    build: ./ml
    container_name: flexora-ml-api
    ports:
      - "5000:5000"

  backend-api:
    build: ./backend
    container_name: flexora-backend-api
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - ml-api

  frontend:
    build: ./frontend
    container_name: flexora-frontend
    ports:
      # Map port 3000 on your computer to port 80 inside the Nginx container.
      - "3000:80"
    depends_on:
      - backend-api
